---
name: AWS Deploy（s3）

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      AWS_BUCKET_NAME:
        required: true

jobs:
  UploadStaticFiles:
    name: Upload static files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: "Configure AWS credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_DEV_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_DEV_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: s3 Sync
      id: s3-sync
      working-directory: src
      run: |
        aws s3 sync . s3://${{ inputs.AWS_BUCKET_NAME }}/
