---
name: AWS Deploy（s3）

on:
  workflow_call:
    inputs:
      kakegoe:
        required: true
        type: string
      hoge:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      AWS_BUCKET_NAME:
        required: true

env:
  yamabiko: ${{ inputs.kakegoe }}

jobs:
  UploadStaticFiles:
    name: Upload static files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: "Configure AWS credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: s3 Sync
      id: s3-sync
      working-directory: src
      run: |
        echo "(1) kakegoe: ${{ inputs.kakegoe }}"
        echo "(2) yamabiko ${{ env.yamabiko }}"
        echo "(3) yamabiko $yamabiko"
        echo "(4) hoge ${{ inputs.region }}"
        aws s3 sync . s3://${{ secrets.AWS_BUCKET_NAME }}/
