---
name: Branch (main)

on:
  push:
    branches:
      - main

jobs:
  manual-message:
    uses: tqer39/example-gha-multi-workflow/.github/workflows/manual-message.yml@main
    with:
      execution_source: "Branch (main)"

  merge-message:
    needs: [manual-message]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: message
      uses: actions/github-script@v6
      id: set-result
      with:
        script: return "main ブランチにマージされた の Actions"
        result-encoding: string

  aws-deploy:
    needs: [merge-message]
    uses: ./.github/workflows/manual-aws-deploy.yml
    with:
      execution_source: "Branch (main)"
