---
name: AWS Deploy（s3）

on:
  workflow_dispatch:

jobs:
  aws-deploy:
    uses: ./.github/workflows/aws-deploy.yml
    with:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      AWS_REGION: ap-northeast-1
