---
name: Manual Message

on:
  workflow_dispatch:
    inputs:
      execution_source:
        description: 'Manual Message'
        required: true
  workflow_call:
    inputs:
      execution_source:
        required: true
        type: string

jobs:
  message:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: message
      uses: actions/github-script@v6
      id: set-result
      with:
        script: return "manual-1 の Actions。実行元 = ${{ inputs.execution_source }}"
        result-encoding: string
